### ISSUE TITLE
syntax error, unexpected '$consumerKey'

### ISSUE THREAD

**Issue by ghost** [AlbertKozlowski/Twitter-php#2]
Hey! I use this code:

```php
<?php
include_once 'creds.php';
require_once 'Twitter-php/RestApi.php';

$twitter = new \TwitterPhp\RestApi($consumerKey,$consumerSecret,$accessToken,$accessTokenSecret);
$connection = $twitter->connectAsApplication();
$tweets = $connection->get('search/tweets', array('q'=>'from:TucoTheCat filter:images','include_entities'=>1));
var_dump($tweets);
?>
```

I get this:
`[Sun Mar 19 10:32:12.937443 2017] [:error] [pid 30514] [client 162.158.90.56:23316] PHP Parse error:  syntax error, unexpected '$consumerKey' (T_VARIABLE) in /var/www/skiilaa.me/public_html/tucolib/creds.php on line 6`

**Comment by AlbertKozlowski** [comment]
Hello!

Please, can you paste content of the creds.php (please remove sensitive data), error indicates that you got an error there.

**Comment by ghost** [comment]
Hey! I already solved the problem.
